# Generated by Django 5.1.3 on 2024-12-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateTimeField(auto_now_add=True, null=True)),
                ('gender', models.BooleanField(default=True)),
                ('nation', models.CharField(max_length=150, null=True)),
                ('singer_profile', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('duration_time', models.CharField(max_length=10, null=True)),
                ('music_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.CharField(max_length=500, null=True)),
                ('artist', models.ManyToManyField(related_name='music_artist', to='app.artist')),
                ('category', models.ManyToManyField(related_name='music_cate', to='app.category')),
                ('playlist', models.ManyToManyField(related_name='music_playlist', to='app.playlist')),
            ],
        ),
    ]
