# Generated by Django 5.1.3 on 2024-12-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_artist_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_link',
            field=models.FileField(default='Tôi hát', upload_to='app/static/app/audio'),
        ),
    ]
