# Generated by Django 5.1.3 on 2024-12-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_music_music_img_alter_music_music_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_img',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/app/images'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_link',
            field=models.FileField(default='Tôi hát', upload_to='app/static/app/audio'),
        ),
    ]
